Document: tcpsleep
Title: Debian tcpsleep Manual
Author: <insert document author here>
Abstract: This manual describes what tcpsleep is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tcpsleep/tcpsleep.sgml.gz

Format: postscript
Files: /usr/share/doc/tcpsleep/tcpsleep.ps.gz

Format: text
Files: /usr/share/doc/tcpsleep/tcpsleep.text.gz

Format: HTML
Index: /usr/share/doc/tcpsleep/html/index.html
Files: /usr/share/doc/tcpsleep/html/*.html
